### ISSUE TITLE
"targetctl clear" fails with Linux 5.18-rc6

### ISSUE THREAD

**Issue by cvubrugier** [open-iscsi/rtslib-fb#185]
I tested LIO with Linux 5.18-rc6 and when running `targetctl clear`, I observed the following error:

    # sudo targetctl clear
    Traceback (most recent call last):
      File "/usr/bin/targetctl", line 82, in <module>
        main()
      File "/usr/bin/targetctl", line 79, in main
        funcs[sys.argv[1]](savefile)
      File "/usr/bin/targetctl", line 57, in clear
        RTSRoot().clear_existing(confirm=True)
      File "/usr/lib/python3/dist-packages/rtslib_fb/root.py", line 318, in clear_existing
        so.delete()
      File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 269, in delete
        for lun in self._gen_attached_luns():
      File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 215, in _gen_attached_luns
        for tpgt_dir in listdir(tpgts_base):
    NotADirectoryError: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'

The `cpus_allowed_list` attribute was added to the Linux kernel by this commit: [scsi: target: Add iscsi/cpus_allowed_list in configfs](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d72d827f2f2636d8d72f0f3ebe5b661c9a24d343) before Linux v5.18-rc1.

I will provide a fix for this issue.

**Comment by cvubrugier** [comment]
Sorry, my bug report is invalid. The version of targetcli on Ubuntu I used is too old. The bug is already fixed upstream.
See 94c7057b07cf70b73ed82adafefb73386e3fa71c
