### ISSUE TITLE
rtslib_fb.utils.RTSLibError: Could not create _Backstore in configFS

### ISSUE THREAD

**Issue by lremember** [open-iscsi/rtslib-fb#193]
Dear all:
How can I solve this problem:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rtslib_fb/node.py", line 71, in _create_in_cfs_ine
    os.mkdir(self.path)
OSError: [Errno 22] Invalid argument: '/sys/kernel/config/target/core/rbd_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/PanaStor/core/lio/api.py", line 79, in add_target
    storage_obj = RBDStorageObject(ConfigAPI().get_image_name_prefix() + disk_meta.id, rbd_mapped_path,wwn)
  File "/usr/lib/python3.9/site-packages/rtslib_fb/tcm.py", line 838, in __init__
    super(RBDStorageObject, self).__init__(name, 'create')
  File "/usr/lib/python3.9/site-packages/rtslib_fb/tcm.py", line 66, in __init__
    self._backstore = _Backstore(name, type(self), mode)
  File "/usr/lib/python3.9/site-packages/rtslib_fb/tcm.py", line 1106, in __init__
    self._create_in_cfs_ine(mode)
  File "/usr/lib/python3.9/site-packages/rtslib_fb/node.py", line 73, in _create_in_cfs_ine
    raise RTSLibError("Could not create %s in configFS"
rtslib_fb.utils.RTSLibError: Could not create _Backstore in configFS

**Comment by lremember** [comment]
By the way, the kernel is : Linux node-1 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
