### ISSUE TITLE
AttributeError: 'UUID' object has no attribute 'get_hex'

### ISSUE THREAD

**Issue by arthurzenika** [open-iscsi/rtslib-fb#52]
```
/loopback> create
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 100, in <module>
    main()
  File "/usr/bin/targetcli", line 90, in main
    shell.run_interactive()
  File "/usr/lib/python3/dist-packages/configshell/shell.py", line 948, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3/dist-packages/configshell/shell.py", line 777, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3/dist-packages/configshell/shell.py", line 891, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell/shell.py", line 866, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell/node.py", line 1413, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3/dist-packages/targetcli/ui_target.py", line 183, in ui_command_create
    target = Target(self.rtsnode, wwn, mode='create')
  File "/usr/lib/python3/dist-packages/rtslib/target.py", line 74, in __init__
    self.wwn = generate_wwn(fabric_module.wwn_types[0])
  File "/usr/lib/python3/dist-packages/rtslib/utils.py", line 284, in generate_wwn
    return "naa.5001405" + uuid.uuid4().get_hex()[-9:]
AttributeError: 'UUID' object has no attribute 'get_hex'
```

**Comment by gdbrianlu** [comment]
change to uuid.uuid4().hex
