### ISSUE TITLE
MappedLUN constructor fails

### ISSUE THREAD

**Issue by schegi** [open-iscsi/rtslib-fb#90]
I wanted to create a mapped lun. I got a LUN object (lun) and an NodeACL object (acl). First i tried this:

'MappedLUN(acl, lun.lun, lun)' and it fails with 

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/rtslib/target.py", line 1028, in __init__
    + "a NodeACL object")
rtslib.utils.RTSLibError: The parent_nodeacl parameter must be a NodeACL object

But  do it the other way with:
acl.mapped_lun(lun.lun, lun) it worked.

**Comment by agrover** [comment]
I can't reproduce. Can you give me more detailed steps to try? Also, what is the rtslib version? Thanks.
